default:
    resource: "@MainUserBundle/Controller/DefaultController.php"
    type: annotation
    prefix: /user

bitcoin:
    resource: "@MainUserBundle/Controller/BitcoinController.php"
    type: annotation
    prefix: /user/btc

fiat:
    resource: "@MainUserBundle/Controller/FiatController.php"
    type: annotation
    prefix: /user/fiat

api:
    resource: "@MainUserBundle/Controller/APIController.php"
    type: annotation
    prefix: /api

