services:
    main_user.emservice:
        class: Main\UserBundle\Services\UserService
        arguments:
          entityManager: "@doctrine.orm.entity_manager"

    main_user.bitcoinservice:
        class: Main\UserBundle\Services\BitcoinService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            secret: "%bitcoin_service.secret%"
            apiRoot: "%bitcoin_service.api_root%"
            callback: "%bitcoin_service.callback_url%"

    main_user.registration.form.type:
       class: Main\UserBundle\Form\Type\RegistrationFormType
       arguments: [%fos_user.model.user.class%]
       tags:
          - { name: form.type, alias: main_user_registration }

    fos.user.admin.user:
        class: Main\UserBundle\Admin\Entity\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Members", label: "Users" }
        arguments:
            - ~
            - Main\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [MainMarketBundle] ]
            - [ setUserManager, [@fos_user.user_manager] ]