assetic:
    assets:
        jquery:
            inputs:
                - '%kernel.root_dir%/Resources/public/assets/js/jquery.js'
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/Resources/public/js/bootstrap.min.js'
                - '%kernel.root_dir%/Resources/public/assets/js/holder.js'
        ie_js:
            inputs:
                - '%kernel.root_dir%/Resources/public/assets/js/html5shiv.js'
                - '%kernel.root_dir%/Resources/public/assets/js/respond.min.js'

        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/Resources/public/css/bootstrap.css'
                - '%kernel.root_dir%/Resources/public/css/carousel.css'

        font_bootstrap_glyphicons_eot:
            inputs:
                - '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.eot'
            output: "fonts/glyphicons-halflings-regular.eot"

        font_bootstrap_glyphicons_svg:
            inputs:
                - '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.svg'
            output: "fonts/glyphicons-halflings-regular.svg"

        font_bootstrap_glyphicons_ttf:
            inputs:
                - '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.ttf'
            output: "fonts/glyphicons-halflings-regular.ttf"

        font_bootstrap_glyphicons:
            inputs:
                - '%kernel.root_dir%/Resources/public/fonts/glyphicons-halflings-regular.woff'
            output: "fonts/glyphicons-halflings-regular.woff"