services:
    sonata.admin.config:
        class: Main\SiteBundle\Admin\Entity\ConfigAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "General", label: "Site Config" }
        arguments:
            - ~
            - Main\SiteBundle\Entity\Config
            - ~
        calls:
            - [ setTranslationDomain, [MainSiteBundle]]

    main_site.configSvc:
            class: Main\SiteBundle\Services\ConfigService
            arguments:
              entityManager: "@doctrine.orm.entity_manager"

    main_site.twig.last_price:
            class: Main\SiteBundle\Twig\LastPriceExtension
            arguments:
              cache: "@cache"
            tags:
                - { name: twig.extension }